package vn.loitp.a.demo.ebookWithRealm.md

import androidx.annotation.Keep
import io.realm.RealmObject
import io.realm.annotations.PrimaryKey

@Keep
open class Book : RealmObject() {

    // Standard getters & setters generated by your IDE…
    @PrimaryKey
    open var id: Long = 0

    open var title: String? = null

    open var description: String? = null

    open var author: String? = null

    open var imageUrl: String? = null
}
