buildscript {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        //https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.25"
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

